# Generated by Django 2.1.4 on 2020-07-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('director', models.TextField(blank=True)),
                ('producers', models.TextField(blank=True)),
                ('character', models.ManyToManyField(to='star_universe.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star_universe.Planet'),
        ),
    ]
